language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-rapid-datavis' ]; then cd .. && eval "mv $currentfolder generator-rapid-datavis" && cd generator-rapid-datavis; fi

